<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Version>1.0.0</Version>
        <IsAotCompatible>true</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CatData\CatData.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Extensions\RealityCoProcessor\Shaders\default.frag" />
      <None Remove="Extensions\RealityCoProcessor\Shaders\default.vert" />
      <None Remove="Extensions\Renderer\Shaders\SpriteFragment.frag" />
      <None Remove="Extensions\Renderer\Shaders\TileFragment.frag" />
      <None Remove="Extensions\Renderer\Shaders\TileVertex.vert" />
    </ItemGroup>

</Project>
