<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>catasm</ToolCommandName>
        <PackageId>CatMachine.CatAssembler</PackageId>
        <Title>Cat Assembler</Title>
        <Authors>Serble</Authors>
        <Description>Assembler of the Cat Assembly language.</Description>
        <PackageProjectUrl>https://github.com/Serble/CatMachine</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/Serble/CatMachine/blob/main/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/Serble/CatMachine</RepositoryUrl>
        <Version>1.0.0</Version>

        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\CatData\CatData.csproj" />
      <ProjectReference Include="..\IntegerMaths\IntegerMaths.csproj" />
    </ItemGroup>
</Project>
