<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Catnip.Compiler</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CatAssembler\CatAssembler.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="std.cc">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Include="test.cc">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Sprache" Version="3.0.0-develop-00049" />
    </ItemGroup>

</Project>
