<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>nipcompile</ToolCommandName>
        <RootNamespace>Catnip.Compiler</RootNamespace>
        <PackageId>CatMachine.Catnip.Compiler</PackageId>
        <Title>Catnip Compiler</Title>
        <Authors>Serble</Authors>
        <Description>Compiler for Catnip, the language that is designed for Cat Machine.</Description>
        <PackageProjectUrl>https://github.com/Serble/CatMachine</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/Serble/CatMachine/blob/main/LICENSE</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/Serble/CatMachine</RepositoryUrl>
        <Version>1.0.0</Version>

        <IncludeSymbols>true</IncludeSymbols>
        <IncludeSource>true</IncludeSource>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CatAssembler\CatAssembler.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Sprache" Version="3.0.0-develop-00049" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Libraries\std.nip" />
      <EmbeddedResource Include="Libraries\ppu.nip" />
      <None Remove="Libraries\hardware.nip" />
      <EmbeddedResource Include="Libraries\hardware.nip" />
    </ItemGroup>

</Project>
