//===-- CatInstPrinter.h - Convert Cat MCInst to asm syntax ----*- C++ -*-===//
//
// Part of the LLVM Project
//
//===----------------------------------------------------------------------===//
//
// This class prints a Cat MCInst to a .s file.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_LIB_TARGET_CAT_MCTARGETDESC_CATINSTPRINTER_H
#define LLVM_LIB_TARGET_CAT_MCTARGETDESC_CATINSTPRINTER_H

#include "llvm/MC/MCInstPrinter.h"

namespace llvm {

class CatInstPrinter : public MCInstPrinter {
public:
  CatInstPrinter(const MCAsmInfo &MAI, const MCInstrInfo &MII,
                 const MCRegisterInfo &MRI)
      : MCInstPrinter(MAI, MII, MRI) {}

  void printInst(const MCInst *MI, uint64_t Address, StringRef Annot,
                 const MCSubtargetInfo &STI, raw_ostream &O) override;

  void printOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);
  void printMemOperand(const MCInst *MI, unsigned OpNo, raw_ostream &O);

  // Autogenerated by tblgen.
  std::pair<const char *, uint64_t> getMnemonic(const MCInst *MI) override;
  void printInstruction(const MCInst *MI, uint64_t Address, raw_ostream &O);
  static const char *getRegisterName(unsigned RegNo);
};

} // end namespace llvm

#endif
