; Expected Cat Assembly Output for simple.c
; Generated by LLVM Cat Backend
;
; This is a conceptual example of what the LLVM backend would generate
; for the simple.c example program.

; Function: add
; int add(int a, int b) { return a + b; }
add:
    ; Prologue
    PUSH r4
    PUSH r5
    PUSH r6
    PUSH r7
    SUB sp, 0           ; No local variables
    MOV r7, sp          ; Set frame pointer
    
    ; Function body
    ; r1 = a, r2 = b (passed in by caller)
    ADD r1, r2          ; r1 = a + b
    MOV r0, r1          ; Move result to r0 (return register)
    
    ; Epilogue
    MOV sp, r7
    ADD sp, 0
    POP r7
    POP r6
    POP r5
    POP r4
    RET

; Function: subtract
; int subtract(int a, int b) { return a - b; }
subtract:
    PUSH r4
    PUSH r5
    PUSH r6
    PUSH r7
    SUB sp, 0
    MOV r7, sp
    
    ; r1 = a, r2 = b
    SUB r1, r2          ; r1 = a - b
    MOV r0, r1
    
    MOV sp, r7
    ADD sp, 0
    POP r7
    POP r6
    POP r5
    POP r4
    RET

; Function: multiply
; int multiply(int a, int b) { return a * b; }
multiply:
    PUSH r4
    PUSH r5
    PUSH r6
    PUSH r7
    SUB sp, 0
    MOV r7, sp
    
    ; r1 = a, r2 = b
    UMUL r1, r2         ; r1 = a * b (unsigned multiply)
    MOV r0, r1
    
    MOV sp, r7
    ADD sp, 0
    POP r7
    POP r6
    POP r5
    POP r4
    RET

; Function: main
; int main() { ... }
main:
    PUSH r4
    PUSH r5
    PUSH r6
    PUSH r7
    SUB sp, 12          ; Allocate space for locals: x, y, sum, diff, prod
    MOV r7, sp
    
    ; int x = 10;
    MOV r4, 10
    MOV r5, r7
    MOV @r5, r4         ; Store x at [fp+0]
    
    ; int y = 5;
    MOV r4, 5
    MOV r5, r7
    ADD r5, 4
    MOV @r5, r4         ; Store y at [fp+4]
    
    ; int sum = add(x, y);
    MOV r5, r7
    MOV r1, @r5         ; Load x into r1
    MOV r5, r7
    ADD r5, 4
    MOV r2, @r5         ; Load y into r2
    CALL 0xFF, add      ; Call add function
    MOV r4, r7
    ADD r4, 8
    MOV @r4, r0         ; Store result in sum at [fp+8]
    
    ; Similar code for diff and prod...
    
    ; if (sum > 10)
    MOV r4, r7
    ADD r4, 8
    MOV r1, @r4         ; Load sum
    MOV r2, 10
    CMP r1, r2          ; Compare sum with 10
    JUGE 0xFF, .L_then  ; Jump if sum >= 10
    
    ; else branch (return 1)
    MOV r0, 1
    JMP 0xFF, .L_end
    
.L_then:
    ; return 0
    MOV r0, 0
    
.L_end:
    ; Epilogue
    MOV sp, r7
    ADD sp, 12
    POP r7
    POP r6
    POP r5
    POP r4
    RET
