using Catnip.Compiler.Ast;

namespace Catnip.Compiler.CodeGen;

public partial class CodeGenerator(CatProgram program) {
    private static readonly string[] FileHeaderComments = [
        "=========================================",
        "Assembly code generated by Catnip Compiler",
        "Target architecture: 32bit Cat",
        "========================================="
    ];
    
    /// <summary>
    /// List of global variables with their names and sizes in bytes.
    /// These will be allocated using a d8 directive at the end of the program.
    /// </summary>
    private readonly List<(string Name, int Bytes)> _globals = [];
    
    /// <summary>
    /// Map of local variable names to their offsets from the base pointer.
    /// So the address of a local variable can be found by calculating
    /// [bp - offset].
    ///
    /// Locals don't actually have a size, since they are just offsets from the base pointer.
    /// The size is only needed when they're set or get, but must be specified then.
    /// </summary>
    private readonly Dictionary<string, int> _localVarOffsets = [];
    
    /// <summary>
    /// Current offset from the base pointer for local variable allocation.
    /// </summary>
    private int _currentStackOffset;
    
    /// <summary>
    /// Used to generate unique labels for logic jumps (if/else/while).
    /// </summary>
    private int _logicJumpCounter = 0;

    /// <summary>
    /// List of application strings that have been needed and
    /// will be allocated at the end of the program.
    /// </summary>
    private readonly List<string> _applicationStrings = [];
    
    private const string StringLabelFormat = "_str_{0}";
    
    /// <summary>
    /// Registers that have been used in the current context and must be preserved.
    /// MUST BE RESET when entering a new function.
    /// </summary>
    private readonly List<string> _usedRegisters = [];
    
    /// <summary>
    /// General purpose registers available for use as scratch registers.
    /// </summary>
    private static readonly string[] GeneralPurposeRegisters = [
        "r0", "r1", "r2", "r3", "r4", "r5", "r6"
    ];
    
    private static readonly string[] CallingConventionArgRegisters = [
        "r1", "r2", "r3"
    ];
    
    private const string BasePointerRegister = "r7";
    private const string DefaultReturnRegister = "r0";
    
    /// <summary>
    /// Registers that must be preserved across function calls.
    /// </summary>
    private static readonly string[] CalleeSavedRegisters = [
        "r4", "r5", "r6", "r7"
    ];
    
    /// <summary>
    /// List of general purpose registers that are currently free to use.
    /// r7 is not here because we're going to use it as our base pointer.
    /// </summary>
    private readonly Stack<string> _freeRegisters = new(GeneralPurposeRegisters);
    
    /// <summary>
    /// Allocates a register for use.
    /// If no registers are free, spills one (returns a register that needs to be preserved).
    /// </summary>
    /// <param name="except">Register that must not be given.</param>
    /// <returns>The register that has been allocated and whether it must be preserved.</returns>
    private (string reg, bool preserve) AllocateRegister(params string[] except) {
        Stack<string> tempStack = new();
        bool found = false;
        string? allocatedRegister = null;
        
        // Try to find a free register that is not in the except list
        while (_freeRegisters.Count > 0) {
            string reg = _freeRegisters.Pop();
            if (except.Contains(reg)) {
                tempStack.Push(reg);  // keep it aside
                continue;
            }
            allocatedRegister = reg;
            found = true;
            break;
        }
        
        // Restore other registers
        while (tempStack.Count > 0) {
            _freeRegisters.Push(tempStack.Pop());
        }
        
        if (found && allocatedRegister != null) {
            if (!_usedRegisters.Contains(allocatedRegister)) {
                _usedRegisters.Add(allocatedRegister);  // mark as used by this function
            }
            return (allocatedRegister, false);  // no need to preserve
        }
        
        // No free registers, need to spill one
        // Just pick the first one from the except list that is not already used
        foreach (string reg in GeneralPurposeRegisters) {
            if (except.Contains(reg)) continue;
            if (!_usedRegisters.Contains(reg)) {
                _usedRegisters.Add(reg);  // mark as used by this function
            }
            return (reg, true);  // must preserve
        }
        
        throw new Exception("No registers available to allocate.");
    }
    
    /// <summary>
    /// Allocates a specific register if it is free.
    /// Returns true if successful, false if the register was not free.
    /// If the register was not free it must be preserved.
    /// </summary>
    /// <param name="register">The register to allocate.</param>
    /// <returns>Whether the register must be preserved.</returns>
    private bool AllocateSpecificRegister(string register) {
        if (_freeRegisters.Contains(register)) {
            // Remove from free registers
            Stack<string> tempStack = new();
            while (_freeRegisters.Count > 0) {
                string reg = _freeRegisters.Pop();
                if (reg == register) {
                    break;  // found the register to allocate
                }
                tempStack.Push(reg);
            }
            // Restore other registers
            while (tempStack.Count > 0) {
                _freeRegisters.Push(tempStack.Pop());
            }

            if (!_usedRegisters.Contains(register)) {
                _usedRegisters.Add(register);  // mark as used by this function
            }
            return false;
        }
        return true;  // register was not free
    }
    
    /// <summary>
    /// Frees a register that was previously allocated.
    /// Does not check if the register was already free.
    /// DO NOT free a register that was spilled!
    /// </summary>
    /// <param name="register">The register to return.</param>
    private void FreeRegister(string register) {
        if (_freeRegisters.Contains(register)) {
            return;
        }
        _freeRegisters.Push(register);
    }

    /// <summary>
    /// Gets the label for a string literal, adding it to the application strings always.
    /// It is always added to ensure the user can modify the string later if needed.
    /// </summary>
    /// <param name="str">The string to add.</param>
    /// <returns>The label.</returns>
    private string GetStringLabel(string str) {
        _applicationStrings.Add(str);
        return string.Format(StringLabelFormat, _applicationStrings.Count - 1);
    }
    
    private string GetUniqueLogicLabel() {
        return $".logic_{_logicJumpCounter++}";
    }

    private uint ResolveCompileConstant(CompileTimeValue value) {
        return value switch {
            CompileTimeNumber num => num.Value,
            CompileTimeStructSize structSize => GetStructSize(structSize.StructName),
            _ => throw new Exception("Unknown compile-time value type.")
        };
    }
    
    private uint GetStructSize(string structName) {
        Struct? strct = program.Structs.FirstOrDefault(s => s.Name == structName);
        if (strct == null) {
            throw new Exception($"Unknown struct '{structName}' for size retrieval.");
        }

        uint size = 0;
        foreach (VarNameSize member in strct.Fields) {
            size += ResolveCompileConstant(member.Size);
        }
        return size;
    }

    // ================ CODE GENERATION ==================
    
    public string Generate() {
        AssemblyFileBuilder file = new();
        
        // File header comments
        foreach (string commentLine in FileHeaderComments) {
            file.Comment(commentLine);
        }
        file.BlankLine();
        
        // Generate top-level statements
        // these don't require function prologues/epilogues
        foreach (Statement topLevelStatement in program.TopLevelStatements) {
            GenerateStatement(topLevelStatement, file, false);
        }
        
        _usedRegisters.Clear();  // reset used registers for functions

        foreach (Function function in program.Functions) {
            GenerateFunction(function, file);
        }
        
        // Allocate global variables
        file.BlankLine();
        file.Comment("Global variable allocations");
        foreach ((string name, int bytes) in _globals) {
            file.Label(name);
            file.AppendIndented($"res8 {bytes}");
        }
        
        // Allocate application strings
        if (_applicationStrings.Count > 0) {
            file.BlankLine();
            file.Comment("Application strings");
            for (int i = 0; i < _applicationStrings.Count; i++) {
                string str = _applicationStrings[i];
                string label = string.Format(StringLabelFormat, i);
                file.Label(label);
                byte[] strBytes = System.Text.Encoding.ASCII.GetBytes(str);
                string byteList = string.Join(", ", strBytes.Select(b => b.ToString()));
                file.AppendIndented($"d8 {byteList}, 0  ; null-terminated string");
            }
        }
        
        return file.ToString();
    }

    private void GenerateFunction(Function function, AssemblyFileBuilder file) {
        // Reset state for new function
        _usedRegisters.Clear();
        _localVarOffsets.Clear();
        _currentStackOffset = 0;
        
        // To know the stack layout, we'll need to generate the body
        // twice, first pass to determine stack size (what registers need to be saved),
        // then we can put all the stack args into locals and regenerate the body
        // with the correct offsets.
        
        // =====================================
        //            FIRST PASS
        // =====================================
        // we need all the parameters in the map but they can be at dummy offsets for now
        // and we'll fix them later
        foreach (VarNameSize param in function.Parameters) {
            _localVarOffsets[param.Name] = 0; // dummy offset
            _currentStackOffset += 1;  // dummy to ensure that the base pointer is preserved
        }
        
        // Generate the body to see which registers are used
        AssemblyFileBuilder tempBody = new();
        foreach (Statement statement in function.Statements) {
            GenerateStatement(statement, tempBody);
        }
        
        // let's record all the information we have so far
        int preservedRegisterCount = _usedRegisters.Count(usedReg => CalleeSavedRegisters.Contains(usedReg));
        if (_currentStackOffset > 0) {
            // we have locals, so we need to preserve the base pointer too
            preservedRegisterCount += 1;
        }
        
        // stack args are pushed by the caller before the call instruction
        // so there will be a ret address, and all our preserved registers
        int stackSpaceBeforeStackArgs = 4 * (1 + preservedRegisterCount); // 4 bytes per item
        // bp - stackSpaceBeforeStackArgs will be the return address location
        
        // =====================================
        //           SECOND PASS
        // =====================================
        // Reset state for second pass
        _usedRegisters.Clear();
        _localVarOffsets.Clear();
        _currentStackOffset = 0;
        
        // Add function parameters as local variables (only first 3 in registers)
        // the rest are already on the stack.
        for (int i = 0; i < function.Parameters.Length; i++) {
            VarNameSize param = function.Parameters[i];
            
            if (i >= CallingConventionArgRegisters.Length) {
                // Stack argument
                // get the negative offset from base pointer
                int offsetFromBp = stackSpaceBeforeStackArgs + 4 * (i - CallingConventionArgRegisters.Length + 1);
                _localVarOffsets[param.Name] = -offsetFromBp;
                continue;
            }
            
            // Register argument
            _currentStackOffset += (int)ResolveCompileConstant(param.Size);
            _localVarOffsets[param.Name] = _currentStackOffset;
        }

        // Get the body first to know which registers are used
        AssemblyFileBuilder body = new();
        foreach (Statement statement in function.Statements) {
            GenerateStatement(statement, body);
        }
        
        // now we have the body, and also know which registers were used
        // we can generate the prologue and epilogue
        // we also don't need to bother with the base pointer if there are no locals
        AssemblyFileBuilder prologue = new();
        prologue.Comment("Function prologue", true);
        
        Stack<string> preservedRegisters = new();
        if (_currentStackOffset != 0) {
            prologue.AppendIndented($"push {BasePointerRegister}");
            preservedRegisters.Push(BasePointerRegister);
        }
        
        // PARAM SETUP (before register preservation because it uses a scratch register)
        
        AssemblyFileBuilder paramSetup = new();
        if (function.Parameters.Length > 0) paramSetup.Comment("Placing arguments into local variables", true);
        (string Reg, bool Preserve)? paramSettingScratch = null;
        for (int i = 0; i < function.Parameters.Length; i++) {
            VarNameSize param = function.Parameters[i];
            if (i >= CallingConventionArgRegisters.Length) {
                // Stack argument
                // already on the stack, nothing to do
                continue;
            }
            
            // Register argument
            if (paramSettingScratch == null) {
                paramSettingScratch = AllocateRegister(except: CallingConventionArgRegisters);
                if (paramSettingScratch.Value.Preserve) {
                    paramSetup.AppendIndented($"push {paramSettingScratch.Value.Reg}  ; preserve scratch register for parameter setup");
                }
            }
            
            string argReg = CallingConventionArgRegisters[i];
            int offset = _localVarOffsets[param.Name];
            paramSetup.AppendIndented($"mov {paramSettingScratch.Value.Reg}, {BasePointerRegister}");
            paramSetup.AppendIndented($"sub {paramSettingScratch.Value.Reg}, {offset}  ; address of parameter '{param.Name}'");
            paramSetup.AppendIndented($"mov [{paramSettingScratch.Value.Reg}], {argReg}  ; store parameter '{param.Name}'");
        }

        if (paramSettingScratch != null) {
            if (paramSettingScratch.Value.Preserve) {
                paramSetup.AppendIndented($"pop {paramSettingScratch.Value.Reg}  ; restore scratch register after parameter setup");
            }
            FreeRegister(paramSettingScratch.Value.Reg);
        }
        
        paramSetup.BlankLine();
        
        // END OF PROLOGUE

        foreach (string usedReg in _usedRegisters.Where(r => CalleeSavedRegisters.Contains(r))) {
            prologue.AppendIndented($"push {usedReg}");
            preservedRegisters.Push(usedReg);
        }
        
        if (_currentStackOffset != 0) {
            prologue.AppendIndented($"mov {BasePointerRegister}, sp");
            prologue.AppendIndented($"sub sp, {_currentStackOffset}  ; allocate space for locals");
        }
        
        // EPILOGUE
        
        AssemblyFileBuilder epilogue = new();
        epilogue.BlankLine();
        epilogue.Comment("Function epilogue", true);
        epilogue.Label(".end");
        if (_currentStackOffset != 0) epilogue.AppendIndented($"mov sp, {BasePointerRegister}  ; deallocate locals");
        
        while (preservedRegisters.Count > 0) {
            string reg = preservedRegisters.Pop();
            epilogue.AppendIndented($"pop {reg}  ; restore preserved register");
        }
        
        epilogue.AppendIndented("ret");
        
        // Now assemble the full function
        file.BlankLine();
        file.BlankLine();
        file.Comment("Function: " + function.Name);
        foreach (VarNameSize param in function.Parameters) {
            file.Comment("Parameter: " + param.Name + " (" + ResolveCompileConstant(param.Size) + " bytes)");
        }
        file.Label(function.Name);
        file.Append(prologue);
        file.Append(paramSetup);
        file.Append(body);
        file.Append(epilogue);
        file.BlankLine();
        file.BlankLine();
    }
}
